FROM chuanwen/cowsay:latest
ENTRYPOINT [ "/usr/games/cowsay" ]
CMD [ "#VQV Trybe" ]

# Instrucoes - 
# fazer o build do dockerfile
# subir o container:
#   primeiro sem nenhum comando adicional: docker container run cowsay (vai escrever o que esta definido no CMD)
#   depois, subir um container passando uma mensagem como: docker container run cowsay Muuuuuuhhh
#   além da mensagem você pode utilizar a opção -l para listar outros personagens disponíveis e então executar algo como docker container run cowsay -f dragon-and-cow "VQV TRYBE", para exibir um dragão junto com a vaquinha.